set schema 'parcoursup';

Drop table if exists stockage;
create table stockage(
  Session int ,
  Statut_etablissement Varchar(50),
  Code_UAI_etablissement Varchar(20),
  etablissement_libelle Varchar(50),
  etablissement_code_dept Varchar(20),
  dept_nom Varchar(20),
  region_nom Varchar(20),
  academie_nom Varchar(20),
  commune_nom Varchar(50),
  filiere_libelle Varchar(50),
  selectivite Varchar(50),
  filiere_libelle_tres_abrege varchar(20),
  filiere_detaille varchar(50),
  filiere_libelle_abrege varchar(50),
  filiere_libelle_detaille_bis varchar(50),
  coordonnees_gps varchar(20),
  capacite int,
  effectif_total_candidats int,
  effectif_total_candidates int,
  effectif_candidats_neo_bac_classes_type_general int,
  effectif_candidats_neo_bac_boursiers_classes_type_general int,
  effectif_candidats_neo_bac_classes_type_techno int,
  effectif_candidats_neo_bac_boursiers_classes_type_techno int,
  effectif_candidats_neo_bac_classes_type_pro int,
  effectif_candidats_neo_bac_boursiers_classes_type_pro int,
  effectif_candidats_classes_type_autres int,
  effectif_total_proposition_admission int,
  effectif_total_admis int,
  effectif_total_admises int,
  effectif_total_admis_boursiers_neo_bac int,
  effectif_total_admis_neo_bac int,
  effectif_admis_neo_bac_type_general int,
  effectif_admis_neo_bac_type_techno int,
  effectif_admis_neo_bac_type_pro int,
  effectif_admis_neo_bac int,
  effectif_admis_neo_bac_selon_mention_type_mention_sans_info int,
  effectif_admis_neo_bac_selon_mention_type_mention_sans_mention int,
  effectif_admis_neo_bac_selon_mention_type_mention_assez_bien int,
  effectif_admis_neo_bac_selon_mention_type_mention_bien int,
  effectif_admis_neo_bac_selon_mention_type_mention_tres_bien int,
  effectif_admis_neo_bac_selon_mention_type_mention_tres_bien_fel int,
  effectif_admis_neo_bac_avec_mention_type_bac_general int,
  effectif_admis_neo_bac_avec_mention_type_bac_techno int,
  effectif_admis_neo_bac_avec_mention_type_bac_pro int,
  effectif_admis_meme_etablissement int,
  effectif_admises_meme_etablissement int,
  effectif_admis_meme_academie int,
  effectif_admis_meme_academie_pcv int,
  regroupement_1 varchar(50),
  rang_dernier_appele_groupe1 int,
  regroupement_2 varchar(50),
  rang_dernier_appele_groupe2 int,
  regroupement_3 varchar(50),
  rang_dernier_appele_groupe3 int,
  list_com varchar(50),
  tri varchar(20),
  cod_aff_form int,
  concours_communs_banques_epreuves varchar(50),
  url_formation varchar(100));

